"""empty message

Revision ID: 96d0ad1442bc
Revises: 
Create Date: 2020-11-30 17:37:54.485268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d0ad1442bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medico', sa.String(length=250), nullable=True),
    sa.Column('paciente', sa.String(length=250), nullable=True),
    sa.Column('horario', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=True),
    sa.Column('especialidade', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pacientes')
    op.drop_table('medicos')
    op.drop_table('consultas')
    # ### end Alembic commands ###
